default: &default
  adapter: mysql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 2968239ms
  host: localhost

development:
  adapter: mysql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 2968239ms
  host: db
  database: dblpoo

test:
  <<: *default
  database: proyectolpoo_test

production:
  <<: *default
  database: proyectolpoo_production
  username: proyectolpoo
  password: <%= ENV['PROYECTOLPOO_DATABASE_PASSWORD'] %>
